version: '3'

services:
  microtask.project:
    image: microtask.project:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.project$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\MicroTask.Project:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.project$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.project$ bin\\Debug\\netcoreapp2.0\\MicroTask.Project.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

  microtask.task:
    image: microtask.task:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.task$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask.Task:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.task$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.task$ bin\\Debug\\netcoreapp1.1\\MicroTask.Task.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  microtask.workjournal:
    image: microtask.workjournal:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.workjournal$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\MicroTask.WorkJournal:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.workjournal$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.workjournal$ bin\\Debug\\netcoreapp1.1\\MicroTask.WorkJournal.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

