version: '3'

services:
  configservice:
    image: configservice:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_configservice$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\ConfigService:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_configservice$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_configservice$ bin\\Debug\\netcoreapp1.1\\ConfigService.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

  microtask.project:
    image: microtask.project:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.project$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\MicroTask.Project:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.project$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.project$ bin\\Debug\\netcoreapp2.0\\MicroTask.Project.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  microtask.rediscache:
    image: microtask.rediscache:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.rediscache$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\MicroTask.RedisCache:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.rediscache$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.rediscache$ bin\\Debug\\netcoreapp2.0\\MicroTask.RedisCache.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  microtask.workjournal:
    image: microtask.workjournal:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.workjournal$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask\MicroTask.WorkJournal:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.workjournal$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.workjournal$ bin\\Debug\\netcoreapp1.1\\MicroTask.WorkJournal.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"


  microtask.worktask:
    image: microtask.worktask:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microtask.worktask$
    volumes:
      - C:\project\micro_service\MicroTask\MicroTask.WorkTask:C:\app
      - C:\Users\JimmyPoor\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_microtask.worktask$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microtask.worktask$ bin\\Debug\\netcoreapp2.0\\MicroTask.WorkTask.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

